[versions]
agp = "8.13.2"
kotlin = "2.3.0"
composeBom = "2025.12.01"
activityCompose = "1.12.2"
lifecycleRuntimeKtx = "2.10.0"
coreKtx = "1.17.0"
navigationCompose = "2.9.6"
datastorePreferences = "1.3.0-alpha03"
coilCompose = "2.7.0"
documentfile = "1.1.0"
accompanistNavigationAnimation = "0.36.0"
rendering = "1.17.1"
kotlinxSerializationJson = "1.9.0"
taglibVersion = "1.0.5"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanistNavigationAnimation" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
sceneform-rendering = { module = "com.google.ar.sceneform:rendering", version.ref = "rendering" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kyant0-taglib = { group = "io.github.kyant0", name = "taglib", version.ref = "taglibVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
